language: python

python:
 - 3.6

install:
 - pip install -r requirements.txt
 - pip install pep8

script:
 - pytest --pylint
 - python manage.py runserver

notifications:
 email:
   - ppenmet@ncsu.edu
   - sadhika2@ncsu.edu
   - sray9@ncsu.edu
   - nshukla2@ncsu.edu
